export const MIGRATION_JOB_TITLES = [
  "Operations Manager",
  "Logistics Manager",
  "Supply Chain Manager",
  "Fleet Manager",
  "Warehouse Manager",
  "Branch Manager",
  "General Manager – Operations",
  "Assistant Manager – Logistics",
  "Deputy Manager Operations",
  "Area Operations Manager",
  "Transport Manager",
  "Fleet Coordinator",
  "Fleet Operations Manager",
  "Transport Supervisor",
  "Fleet Maintenance Manager",
  "Traffic Manager",
  "Transport Executive",
  "Fleet Incharge",
  "Transport Operations Manager",
  "Logistics Coordinator",
  "Warehouse Supervisor",
  "Warehouse Incharge",
  "Store Manager",
  "Warehouse Executive",
  "Inventory Manager",
  "Store Incharge",
  "Warehouse Operations Manager",
  "Distribution Manager",
  "Hub Manager",
  "Warehouse Assistant Manager",
  "Operations Executive",
  "Dispatch Manager",
  "Operations Supervisor",
  "Dispatch Executive",
  "Operations Coordinator",
  "Logistics Executive",
  "Operation Incharge",
  "Dispatch Supervisor",
  "Operations Assistant",
  "Hub Executive",
  "MIS Executive",
  "Fleet Executive",
  "Tracking Executive",
  "Billing Executive",
  "Documentation Executive",
  "Procurement Manager",
  "Vendor Manager",
  "Supply Chain Executive",
  "Logistics Supervisor",
  "Quality Control",
  "Logistics Assistant",
  "Operation Assistant",
  "Warehouse Associate",
  "Data Entry Operator",
  "Computer Operator",
  "Loading Supervisor",
  "Delivery Executive",
  "Hub Associate",
  "Back Office Executive",
  "Customer Service Executive",
]

export const MIGRATION_SKILLS = [
  "MIS",
  "SAP",
  "Excel",
  "ERP",
  "GPS",
  "Tally",
  "TMS",
  "WMS",
  "MS Office",
  "Delivery",
  "Tracking",
  "Dispatch",
  "Logistics",
  "Coordination",
  "Transportation",
  "Loading",
  "Unloading",
  "Inventory Management",
  "Fleet Management",
  "Warehouse Management",
  "Material Handling",
  "Route Planning",
  "Documentation",
  "Compliance",
  "Billing",
  "POD",
  "GRN",
  "E-way Bill",
  "GST",
  "Customs",
  "Reporting",
  "Communication",
  "Procurement",
  "Negotiation",
  "Vendor Management",
  "Vehicle Tracking",
  "Team Management",
  "Cost Reduction",
  "FTL",
  "PTL",
  "LTL",
  "Supply Chain Management",
  "Cold chain logistics",
  "E-commerce logistics",
  "Reverse logistics",
  "International freight forwarding",
  "Last mile delivery",
]

export const INTERNAL_SEARCH_SUGGESTIONS = Array.from(new Set([...MIGRATION_JOB_TITLES, ...MIGRATION_SKILLS]))

export function getSuggestionMatches(input: string, suggestions: string[], limit = 10) {
  const q = input.trim().toLowerCase()
  const base = q
    ? suggestions.filter((s) => s.toLowerCase().includes(q))
    : suggestions
  return base.slice(0, Math.max(1, limit))
}

